#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "$APP_DB_USER" WITH PASSWORD '$APP_DB_PASS';
	GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$APP_DB_USER";
	\c "$POSTGRES_DB"
	GRANT ALL ON SCHEMA public TO "$APP_DB_USER";
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$APP_DB_USER";
EOSQL
